In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.model_selection import GridSearchCV
from sklearn.utils import resample
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA
import seaborn as sns
import numpy as np
import pickle
from sklearn.ensemble import RandomForestRegressor

from sklearn.linear_model import LinearRegression

import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import FactorAnalysis
from factor_analyzer import FactorAnalyzer

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_auc_score

%matplotlib inline

from sklearn.preprocessing import OneHotEncoder
import lightgbm as lgb
from lightgbm import LGBMClassifier 

from sklearn.utils import class_weight
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn.decomposition import TruncatedSVD

import plotly.express as px
import plotly.graph_objs as go
import statsmodels.formula.api as smf
from plotly.graph_objects import Layout

In [2]:
df = pd.read_csv("mergedData.csv")

In [142]:
df = df.drop("Unnamed: 0", axis = 1)

In [143]:
df = df.drop(["DriverNumber", "Driver", "Points"], axis = 1)
# df = df.drop(["DriverNumber", "Driver", "Position"], axis = 1)
aux = df

In [144]:
# create new columns based on Status values
df['carIssue'] = (df['Status'] == 'carIssue').astype(int)
df['driverIssue'] = (df['Status'] == 'driverIssue').astype(int)
df = df.drop('Status', axis=1)

In [145]:
df["RaceCountry"] = df["RaceCountry"].str.replace(" ", "")
df["TeamName"] = df["TeamName"].str.replace(" ", "")
# df = df.drop(["Engine"], axis = 1)
df["Engine"] = df["Engine"].str.replace(" ", "")

In [146]:

# get a list of all categorical variables except "Abbreviation" and "raceID"
cat_vars = df.select_dtypes(include=['object']).columns.tolist()
cat_vars.remove("Abbreviation")
cat_vars.remove("RaceCountry")

# create dummy variables for all categorical variables except "Abbreviation" and "raceID"
dummies = pd.get_dummies(df[cat_vars], drop_first=True)

# drop the original categorical variables from the DataFrame
df = df.drop(cat_vars, axis=1)

# concatenate the dummy variables with the remaining variables in the DataFrame
df = pd.concat([df, dummies], axis=1)

In [148]:
#df = df.drop(["Year", "AverageRPM"], axis = 1)
df = df.drop(["AverageRPM"], axis = 1)
df = df.drop(["AvgLapTime"], axis = 1)
df = df.drop(["AvgSplitTime"], axis = 1)

In [149]:
df

,Abbreviation,Position,GridPosition,RaceCountry,Year,AgeAtGP,BestQualiTime,FLap,SDLapTime,AvgPitTime,...,TeamName_RacingPoint,TeamName_RedBullRacing,TeamName_Renault,TeamName_ToroRosso,TeamName_Williams,Engine_Honda,Engine_Mercedes,Engine_RedBull,Engine_Renault,CircuitType_street
0,GAS,11.0,17.0,Australia,2019.0,22.0,83.020,0.0,2.723962,21.2690,...,0,1,0,0,0,1,0,0,0,1
1,PER,13.0,10.0,Australia,2019.0,29.0,82.532,0.0,2.908751,23.2340,...,1,0,0,0,0,0,1,0,0,1
2,LEC,5.0,5.0,Australia,2019.0,21.0,81.442,0.0,2.795510,22.3060,...,0,0,0,0,0,0,0,0,0,1
3,STR,9.0,16.0,Australia,2019.0,20.0,83.017,0.0,2.711268,22.4710,...,1,0,0,0,0,0,1,0,0,1
4,MAG,6.0,7.0,Australia,2019.0,26.0,82.099,0.0,2.795637,22.3880,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1542,VET,10.0,9.0,AbuDhabi,2022.0,35.0,84.961,0.0,3.057131,23.1860,...,0,0,0,0,0,0,1,0,0,0
1543,SAI,4.0,4.0,AbuDhabi,2022.0,28.0,84.242,0.0,3.799668,21.7525,...,0,0,0,0,0,0,0,0,0,0
1544,LAT,19.0,20.0,AbuDhabi,2022.0,27.0,86.054,0.0,6.817590,23.7985,...,0,0,0,0,1,0,1,0,0,0
1545,RUS,5.0,6.0,AbuDhabi,2022.0,23.0,84.511,0.0,4.489247,26.0870,...,0,0,0,0,0,0,1,0,0,0
1546,BOT,15.0,18.0,AbuDhabi,2022.0,33.0,85.892,0.0,3.036278,22.5730,...,0,0,0,0,0,0,0,0,0,0

In [150]:
#df.to_csv(r'df_points.csv', index=True, header=True)
#df.to_csv(r'df_position.csv', index=True, header=True)
#df.to_csv(r'plotdata_points.csv', index=True, header=True)
#df.to_csv(r'plotdata_position.csv', index=True, header=True)

## MERF

In [152]:
from merf import MERF

In [157]:
# Split the data into two datasets based on the Year column
df_before = df[df['Year'].isin([2019, 2020])]
df_after = df[df['Year'].isin([2021, 2022])]

## Before model

In [158]:
df_before["raceID"]

0       1
1       1
2       1
3       1
4       1
       ..
717    37
718    37
719    37
720    37
721    37
Name: raceID, Length: 722, dtype: int64

In [159]:
# Split the data into train and test sets based on the raceID column
train_df = df_before[(df_before['raceID'] >= 1) & (df_before['raceID'] <= 29)]
test_df = df_before[(df_before['raceID'] >= 30) & (df_before['raceID'] <= 37)]

In [160]:
X_train = train_df.drop('Position', axis=1)
Y_train = train_df['Position']
X_test = test_df.drop('Position', axis=1)
Y_test = test_df['Position']

In [161]:
X_train = X_train.drop('RaceCountry', axis=1)
X_train = X_train.drop('Year', axis=1)
X_test = X_test.drop('RaceCountry', axis=1)
X_test = X_test.drop('Year', axis=1)

In [162]:
x_train = X_train.drop(['Abbreviation', 'raceID'], axis = 1)
Z_train = X_train[['raceID']]
clusters_train = X_train['raceID']

In [163]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

mrf = MERF(fixed_effects_model=model, max_iterations=30)

mrf.fit(x_train, Z_train, clusters_train, Y_train)

INFO     [merf.py:307] Training GLL is 1596.4646623331869 at iteration 1.
INFO     [merf.py:307] Training GLL is 1551.7884174971261 at iteration 2.
INFO     [merf.py:307] Training GLL is 1542.105886004856 at iteration 3.
INFO     [merf.py:307] Training GLL is 1538.0425715316378 at iteration 4.
INFO     [merf.py:307] Training GLL is 1536.2229205798524 at iteration 5.
INFO     [merf.py:307] Training GLL is 1535.3740519146759 at iteration 6.
INFO     [merf.py:307] Training GLL is 1534.9766138964126 at iteration 7.
INFO     [merf.py:307] Training GLL is 1534.7997873223103 at iteration 8.
INFO     [merf.py:307] Training GLL is 1534.732889336695 at iteration 9.
INFO     [merf.py:307] Training GLL is 1534.7207718824654 at iteration 10.
INFO     [merf.py:307] Training GLL is 1534.7353817557064 at iteration 11.
INFO     [merf.py:307] Training GLL is 1534.7622258925526 at iteration 12.
INFO     [merf.py:307] Training GLL is 1534.7937351805408 at iteration 13.
INFO     [merf.py:307] Training GLL is 1534.8259542519334 at iteration 14.
INFO     [merf.py:307] Training GLL is 1534.8568574226051 at iteration 15.
INFO     [merf.py:307] Training GLL is 1534.8854701813634 at iteration 16.
INFO     [merf.py:307] Training GLL is 1534.9113977056375 at iteration 17.
INFO     [merf.py:307] Training GLL is 1534.9345646080378 at iteration 18.
INFO     [merf.py:307] Training GLL is 1534.9550677722707 at iteration 19.
INFO     [merf.py:307] Training GLL is 1534.9730917115735 at iteration 20.
INFO     [merf.py:307] Training GLL is 1534.988859534729 at iteration 21.
INFO     [merf.py:307] Training GLL is 1535.0026046954904 at iteration 22.
INFO     [merf.py:307] Training GLL is 1535.0145550895893 at iteration 23.
INFO     [merf.py:307] Training GLL is 1535.0249245599853 at iteration 24.
INFO     [merf.py:307] Training GLL is 1535.0339088513647 at iteration 25.
INFO     [merf.py:307] Training GLL is 1535.0416842119437 at iteration 26.
INFO     [merf.py:307] Training GLL is 1535.0484075340692 at iteration 27.
INFO     [merf.py:307] Training GLL is 1535.0542173493845 at iteration 28.
INFO     [merf.py:307] Training GLL is 1535.059235257529 at iteration 29.
INFO     [merf.py:307] Training GLL is 1535.0635675322178 at iteration 30.

In [164]:
train_preds = mrf.predict(x_train, Z_train, clusters_train)

In [165]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(Y_train, train_preds)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_train, train_preds)
r2 = r2_score(Y_train, train_preds)

# Print the performance metrics
print("Test MSE:", mse)
print("Test RMSE:", rmse)
print("Test MAE:", mae)
print("Test R-squared:", r2)


# Calculate the RMSPE
mse = mean_squared_error(Y_train, train_preds)
rmspe = np.sqrt(mse / np.mean(Y_train**2))

# Print the RMSPE
print("Test RMSPE:", rmspe)

Test MSE: 7.087361983712685
Test RMSE: 2.6622099811458684
Test MAE: 2.0889718378656745
Test R-squared: 0.7823832377183746
Test RMSPE: 0.22529975232393407

# Test dataset

In [166]:
x_test = X_test.drop(['Abbreviation', 'raceID'], axis = 1)
Z_test = X_test[['raceID']]
clusters_test = X_test['raceID']

In [167]:
x_test

,GridPosition,AgeAtGP,BestQualiTime,FLap,SDLapTime,AvgPitTime,PitstopNo,HARD,INTERMEDIATE,MEDIUM,...,TeamName_RacingPoint,TeamName_RedBullRacing,TeamName_Renault,TeamName_ToroRosso,TeamName_Williams,Engine_Honda,Engine_Mercedes,Engine_RedBull,Engine_Renault,CircuitType_street
568,9.0,24.0,93.000,0.0,4.414441,29.5895,2.0,24.0,0.0,11.0,...,0,0,0,0,0,0,0,0,0,1
569,4.0,30.0,92.317,0.0,3.598099,29.6020,1.0,33.0,0.0,0.0,...,1,0,0,0,0,0,1,0,0,1
570,10.0,22.0,93.239,0.0,3.308658,30.2610,1.0,25.0,0.0,28.0,...,0,0,0,0,0,0,0,0,0,1
571,18.0,28.0,94.681,0.0,3.643243,30.1880,1.0,33.0,0.0,19.0,...,0,0,0,0,0,0,0,0,0,1
572,15.0,24.0,93.008,0.0,3.737778,30.1610,2.0,26.0,0.0,26.0,...,0,1,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
717,18.0,25.0,98.443,0.0,7.947119,21.8705,2.0,24.0,0.0,30.0,...,0,0,0,0,1,0,1,0,0,0
718,16.0,21.0,98.045,0.0,8.040811,22.0850,1.0,44.0,0.0,10.0,...,0,0,0,0,1,0,1,0,0,0
719,15.0,41.0,97.555,0.0,8.160983,22.0120,1.0,44.0,0.0,10.0,...,0,0,0,0,0,0,0,0,0,0
720,2.0,31.0,95.271,0.0,3.679513,21.5870,1.0,45.0,0.0,10.0,...,0,0,0,0,0,0,1,0,0,0
721,14.0,26.0,97.066,0.0,10.390898,21.4800,1.0,27.0,0.0,27.0,...,0,0,0,0,0,0,0,0,0,0

In [168]:
y_pred = mrf.predict(x_test, Z_test, clusters_test)

In [169]:
from sklearn.metrics import r2_score
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)

# Print the performance metrics
print("Test MSE:", mse)
print("Test RMSE:", rmse)
print("Test MAE:", mae)
print("Test R-squared:", r2)

Test MSE: 34.24464770089943
Test RMSE: 5.851892659721249
Test MAE: 3.869540405529234
Test R-squared: -0.09558628938852576

In [170]:
actual_values = Y_test
predictions = y_pred
# Calculate the mean of actual values
mean_actual = sum(actual_values) / len(actual_values)

# Calculate SSE and SST
sse = sum((actual - pred) ** 2 for actual, pred in zip(actual_values, predictions))
sst = sum((actual - mean_actual) ** 2 for actual in actual_values)

# Calculate R-squared
r2 = 1 - (sse / sst)
r2

-0.09558628938852576

In [171]:
# Calculate R-squared
r = np.corrcoef(predictions, actual_values)[0, 1]
r2 = r**2
r2

0.3716447876071426

In [126]:
Y_test

568     9.0
569     4.0
570     6.0
571    12.0
572    10.0
       ...
717    17.0
718    15.0
719    12.0
720     2.0
721    16.0
Name: Position, Length: 154, dtype: float64

In [125]:
y_pred

array([  9.04458751,   7.76957566,   6.88491012,  14.85751325,
        10.02708778,   8.92706864,   8.38625701,   8.68988687,
         4.17879123,   9.98877399,   3.42938408,   8.68550655,
        16.4578558 ,  15.80292338,  13.97095574,   2.86743789,
        15.08901619,  13.20922514,   7.90857343,   8.3736811 ,
         4.26214832,  12.72749219,  14.09079764,   8.73684935,
        12.47617816,   6.69937475,  16.0988852 ,   2.91093933,
        14.62329593,   2.43472747,   7.66453815,   8.2361505 ,
        13.88298096,  23.80956035,  13.69971291,  11.39181322,
        12.52644823,  11.1431633 ,   6.55138959,   7.65614187,
         4.46145151,  18.33240336,  13.72076547,   5.27009525,
         9.87734549,   7.88737669,   8.87275754,   3.0871852 ,
         8.45110965,   1.08080962,   8.60005794,   6.75996915,
        15.67931405,  13.16422545,  11.53315005,   2.32945253,
        14.16212568,  12.77926804,  16.21960138,   9.843263  ,
         5.56210151,  12.7669672 ,  21.10131682,   6.62228041,
         8.15317936,   7.1626728 ,  20.29329832,  12.02058624,
         8.0644541 ,   2.65973708,   8.96461958,   9.08810533,
        15.03860457,  20.63269149,  12.16121839,   3.15801717,
        14.63284823,  12.61415515,  -4.51240457,  -9.33552527,
        -4.04989638,  -7.87854945,   5.44482443, -12.22442465,
        -6.02851655,  -7.41638509,  -6.29593211, -10.31932974,
        -5.77014458,  -9.83472039,  -5.95761184,  -4.92847582,
        16.96634845,   7.90263748,  -1.61937512,  -6.91237499,
         7.46807202,  10.93739517,   6.76535859,  15.4681051 ,
         8.47232083,  16.89371824,   5.49086939,   8.70522752,
         9.06571382,   9.35884887,   5.44181598,   8.32225441,
         2.95529163,   8.48436938,  10.46599106,  16.3294954 ,
        13.8654844 ,  13.30531327,   5.3108349 ,  13.18430186,
         7.08790119,   7.45570632,   6.76474643,  11.4789243 ,
         6.12044128,   6.23762391,   7.87108577,   7.99515262,
        10.467937  ,   8.27973114,  14.23364494,   6.61453653,
        22.38882337,   3.25077393,  13.95598962,  -0.23588171,
        14.53988582,  11.85548722,   7.31051012,  21.00332908,
         7.3489659 ,   8.02394167,  15.19897552,   4.57114505,
         6.98287574,   8.28729841,   9.33597258,   3.78049215,
         6.56874669,   3.11784357,   7.45773405,  16.11624696,
         7.19514428,  15.84398708,  14.24452743,  12.32753619,
         3.16242092,  11.42055454])

In [57]:
train_preds

array([ 7.09094299,  9.6626787 ,  4.37229868, 10.6785708 , 10.77106915,
        9.85391016, 11.45216322,  9.4955561 , 19.42926404,  4.37506559,
        8.40914779,  1.22229485,  3.3357225 , 20.50552923, 15.00136858,
       10.35981784, -0.10011336, 19.70222717, 16.68558932, 10.55588871,
        7.48726851, 10.71922867,  3.04178925, 11.63765887, 11.32148316,
       11.10336371, 11.24216155, 18.78122784, 15.96490264,  4.90428735,
        8.61166053,  3.31583122,  5.84247723, 16.68779508, 15.35169091,
       11.14136782,  3.08817927, 21.55848094, 15.43459436, 12.66669648,
        5.67327942,  9.40950325,  5.63057141, 11.28919616, 13.54845154,
       19.70000068, 19.18218839,  7.51556153,  5.56336862, 17.79706994,
        2.7050926 ,  5.7249139 , 10.38712305, 15.53174972, 12.18411788,
        2.66864098, 13.26205182, 14.88504629, 12.32986107, 12.16537093,
        7.13555283,  5.59692437,  9.43057629, 13.56227735, 10.41932955,
       17.12633186, 11.15625358, 17.97234522,  3.9664317 ,  8.57732235,
        2.12336634,  4.33685665,  8.00145242, 15.07724271,  9.56810081,
        1.61549131, 21.19313698, 12.96548078, 12.71424179,  4.33856712,
       10.35809449,  5.61494011, 15.85403535, 11.58780802, 10.40775246,
        9.67643713,  7.47101009, 10.92797899,  4.55921292, 16.79279689,
        1.08512506,  5.51948808,  9.13946616, 15.32941619, 12.95406112,
        1.85115809, 10.23516753, 14.68765587, 13.91510768,  4.96241841,
       13.1044295 , 20.45297592, 11.86949675, 10.84746951,  9.61910817,
        8.69588096, 11.7526491 ,  8.1016958 ,  6.58703015,  8.95469364,
        2.91733021,  7.09035903,  8.29493053, 16.94651732, 12.23095535,
        5.86084084, 12.03679904, 17.33420524, 13.08295595,  5.84371842,
       11.67057289,  5.07677355, 11.54483864, 11.53442581, 19.03275729,
       10.66116763,  9.400726  ,  8.93893271,  6.36184289, 16.26226319,
        3.66126908,  4.98111196, 10.06793195, 16.02228051, 14.30060825,
        4.50047712, 12.68982256, 17.45427471, 11.52579672,  6.64156847,
       10.528098  ,  4.97230385, 11.62644727, 14.28195712, 10.60996268,
       12.62720085, 10.93016589,  9.00880652,  5.45646671,  8.00406576,
        3.05895893,  6.26486578,  7.91248472, 16.51274858, 12.27252309,
        2.95973706, 21.54781251, 15.44646342, 12.43350159,  5.94486608,
       10.99600867,  4.59756921, 10.8181809 , 14.70938458, 11.69362997,
       11.55390172, 11.44502862,  9.45232036,  4.15784177,  6.75503483,
        3.71669669,  7.86038476, 11.57146814, 11.81761056, 10.96038223,
        3.71588919, 11.98904132, 15.90115632, 11.1212828 ,  5.53554866,
       11.57104279,  5.62489251, 11.79857122, 22.89537629,  8.92737286,
       11.90859848,  8.99255363,  9.14747289,  5.79665714,  8.66098108,
        1.02810165,  6.36045316,  9.10542595, 14.99679427, 11.74918525,
        1.74619272, 22.42605265, 15.35644845, 19.3517556 , 10.71922144,
       15.20558782,  6.49264751,  9.73137505, 10.59878005,  8.72023364,
       15.98728082, 18.5181612 ,  2.24435285, 16.41790719,  2.57770013,
        9.36239067,  4.93558151,  9.96596691,  8.1931903 ,  9.25305389,
       10.01064497, 11.1110694 ,  9.21208846,  5.6792064 , 11.3140192 ,
        5.3722066 , 12.61350867, 12.34697306, 11.18451761, 11.50139177,
        8.87535474, 12.51921736,  4.16740915,  8.2350861 ,  3.87913242,
        5.28702705,  8.22998117, 15.2298496 , 10.52949848,  4.73513224,
       20.05959667, 15.73246379, 13.66805633,  9.48425817,  8.22602008,
        3.44266992, 11.57098949, 10.98232594,  7.38238217, 11.54553385,
       10.20629171,  9.55244561, 14.86085428,  2.72855755,  4.39566271,
       13.30335364, 12.25401634,  2.74922993, 11.23055534, 11.43710896,
       19.70624903, 11.10170654, 10.80494895,  4.70265829,  9.52980463,
       20.90882366,  5.1083649 , 19.59016694,  7.2194122 ,  7.12164946,
        8.52826813, 11.05601308,  2.20816944,  8.89494614, 16.94352857,
       14.53609203, 12.20834266,  3.06194894, 13.08583676, 15.10709254,
       10.43745275,  9.35008696, 18.86085382,  4.0949371 , 11.96594441,
       12.82836305,  5.31312383, 10.85507641,  9.89878459, 11.18783709,
        4.61495691,  8.03202337,  3.00038196,  4.97472342,  9.18465062,
       24.18236179, 19.30661414,  3.2799502 , 13.55776119, 15.80912976,
       10.75401048, 10.25492294,  8.40982689,  4.58968116,  9.27696573,
       11.78520713,  4.79708003,  8.24228987, 18.52768266,  4.38478606,
        6.43476918,  0.34549181, 13.3198151 ,  6.40108799, 23.02889321,
       12.59109204,  2.48309239, 24.85893849, 12.08840591,  9.00431145,
       11.75623096,  6.20378885,  9.32564218, 15.39880931,  5.16800233,
       10.68746649, 17.12475691, 17.02672072, 14.59085416,  9.47865365,
        3.06701415,  5.30022647,  6.69023226, 15.05691911, 12.88107749,
        3.43219924, 12.16381279, 13.2360059 , 12.65009409, 11.24729619,
       10.39002701,  4.05746344, 10.76828392, 14.00828291,  6.30802543,
       10.89231419, 10.6953268 , 10.28523577,  5.81159214, 16.03650972,
        4.01061062,  4.96682421,  8.69104777, 15.94849545, 21.5550931 ,
        4.33874952, 13.78799498, 16.9383776 , 13.12608296, 16.8542305 ,
        8.59844995,  4.16711186, 10.16634645, 19.63742952,  6.09701795,
       11.10365738, 10.41450722,  8.0464428 ,  4.70244863,  8.24893588,
        2.81994422, 14.40814956,  7.45299465, 15.43280759, 13.17220521,
        3.39444969, 12.18721011, 23.32767914, 12.8332875 ,  8.26250965,
       10.33308296, 15.48020266, 16.94124323, 11.34870061,  4.52441549,
       11.06235935, 11.42246897,  8.95085952,  4.44135046,  8.8902908 ,
        3.75939743, 11.46486921,  9.47876313, 15.85375449, 10.37405234,
       11.41278588, 10.97579095, 17.52448459, 11.11672115,  9.94110708,
        9.77541837,  6.2491276 , 18.60799293, 13.38863523,  5.98913832,
       11.4473714 ,  9.02330014, 10.1609578 ,  4.92416826,  8.39949524,
        1.9587608 ,  6.72302147, 10.01921933, 15.37282464, 13.81014641,
        8.14714313, 14.04608673, 15.45598188, 13.66734138,  6.84653949,
        5.86620486,  4.43630409, 15.45334714, 20.15969408, 15.64169755,
       15.03404762, 16.49999424,  9.43550453, 10.41618277,  4.32416324,
        2.50403683,  5.78379186,  7.34419223, 14.87650886, 20.70083519,
       19.87138752,  0.72360505, 19.09332836, 12.03486503, 17.88765489,
        9.03361472,  7.09406283,  9.0736372 , 10.65101455,  8.10994784,
       10.76996051,  9.38103799,  5.63843285,  9.8707161 ,  3.43455416,
        6.59354031,  9.1937868 , 18.60164491, 14.86373792, 14.28681592,
        5.90904858, 10.59526842, 14.07200201,  8.4491472 ,  4.76162922,
        8.46932285,  8.33470981, 18.94042416,  9.04910981,  9.62315379,
        4.21475665,  7.19702997,  2.26550681,  6.21549777,  8.83641925,
       15.2327162 , 15.55729323, 14.08950967,  4.39500336, 13.04562028,
       12.37372488,  8.04216772,  6.28057794,  9.41716806, 22.60986853,
        7.96445517, 10.25920069,  9.31703153,  9.49330072,  9.70423641,
        5.90231945, 10.06634033,  2.84992006,  8.54516054, 10.64478428,
       17.61260631, 16.01237588, 14.08320063,  3.447803  , 13.7242402 ,
       14.4568871 ,  9.01627505,  8.27198526, 15.13035834,  8.9731232 ,
       13.20299869,  6.88942809,  9.72223551, 10.25314011, 10.61777893,
        5.56829812,  9.42527191,  3.76369233,  6.29395452,  9.2418091 ,
       16.69071738, 15.89864577, 13.87930527,  4.06598379, 14.51290065,
       14.82482665,  8.41488985,  8.96851477,  8.43606657,  9.10500913,
       15.12017556,  4.21463734,  8.52778555,  6.83780866,  8.91718437,
        4.62602183,  9.04819309,  2.30168481,  7.6836193 , 16.16750432,
       23.12533939, 12.68191259,  2.95806342, 13.83958478, 21.26548685,
        6.93089927,  7.33318958, 17.89026092,  5.53799285, 24.11450126,
        6.43927265,  8.48882929,  7.5101563 ,  8.69073139, 13.18615413,
        6.33663538,  3.02648204, 18.2936113 ,  5.60225086, 14.7914895 ,
       14.21614743, 11.71083326,  2.82383185, 13.09184728, 13.62013466,
        6.53602757,  4.33145086, 12.21828711, 21.07191861,  2.95058846,
        6.67428153,  6.59603333, 16.32289797,  6.26779663, -0.81408279,
        7.27511123, 14.99006366, 21.98326363, 13.48695028, 12.19072689,
        0.96717214, 11.00185732, 19.01081536])

In [24]:
df.columns

Index(['Abbreviation', 'Position', 'GridPosition', 'RaceCountry', 'Year',
       'AgeAtGP', 'BestQualiTime', 'FLap', 'SDLapTime', 'AvgPitTime',
       'PitstopNo', 'HARD', 'INTERMEDIATE', 'MEDIUM', 'SOFT', 'WET', 'Rain',
       'AverageSpeed', 'MaxSpeed', 'MaxRPM', 'AverageThrottle',
       'MaxThrottlePct', 'Brake', 'raceID', 'carIssue', 'driverIssue',
       'after_2020', 'TeamName_AlfaRomeoRacing', 'TeamName_AlphaTauri',
       'TeamName_Alpine', 'TeamName_AstonMartin', 'TeamName_Ferrari',
       'TeamName_HaasF1Team', 'TeamName_McLaren', 'TeamName_Mercedes',
       'TeamName_RacingPoint', 'TeamName_RedBullRacing', 'TeamName_Renault',
       'TeamName_ToroRosso', 'TeamName_Williams', 'CircuitType_street'],
      dtype='object')

## After model

In [172]:
df_after["raceID"]

722     38
723     38
724     38
725     38
726     38
        ..
1542    80
1543    80
1544    80
1545    80
1546    80
Name: raceID, Length: 825, dtype: int64

In [173]:
df_after

,Abbreviation,Position,GridPosition,RaceCountry,Year,AgeAtGP,BestQualiTime,FLap,SDLapTime,AvgPitTime,...,TeamName_RacingPoint,TeamName_RedBullRacing,TeamName_Renault,TeamName_ToroRosso,TeamName_Williams,Engine_Honda,Engine_Mercedes,Engine_RedBull,Engine_Renault,CircuitType_street
722,GAS,17.0,5.0,Bahrain,2021.0,24.0,89.809,0.0,9.870618,29.212667,...,0,0,0,0,0,0,0,0,0,0
723,PER,5.0,20.0,Bahrain,2021.0,31.0,90.659,0.0,9.238201,24.096333,...,0,1,0,0,0,1,0,0,0,0
724,ALO,19.0,9.0,Bahrain,2021.0,39.0,90.249,0.0,9.050427,24.574000,...,0,0,0,0,0,0,0,0,1,0
725,LEC,6.0,4.0,Bahrain,2021.0,23.0,89.678,0.0,7.326363,24.550500,...,0,0,0,0,0,0,0,0,0,0
726,STR,10.0,10.0,Bahrain,2021.0,22.0,90.601,0.0,9.904268,25.204500,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1542,VET,10.0,9.0,AbuDhabi,2022.0,35.0,84.961,0.0,3.057131,23.186000,...,0,0,0,0,0,0,1,0,0,0
1543,SAI,4.0,4.0,AbuDhabi,2022.0,28.0,84.242,0.0,3.799668,21.752500,...,0,0,0,0,0,0,0,0,0,0
1544,LAT,19.0,20.0,AbuDhabi,2022.0,27.0,86.054,0.0,6.817590,23.798500,...,0,0,0,0,1,0,1,0,0,0
1545,RUS,5.0,6.0,AbuDhabi,2022.0,23.0,84.511,0.0,4.489247,26.087000,...,0,0,0,0,0,0,1,0,0,0
1546,BOT,15.0,18.0,AbuDhabi,2022.0,33.0,85.892,0.0,3.036278,22.573000,...,0,0,0,0,0,0,0,0,0,0

In [174]:
# Split the data into train and test sets based on the raceID column
train_df = df_after[(df_after['raceID'] >= 38) & (df_after['raceID'] <= 72)]
test_df = df_after[(df_after['raceID'] >= 73) & (df_after['raceID'] <= 80)]

In [175]:
X_train = train_df.drop('Position', axis=1)
Y_train = train_df['Position']
X_test = test_df.drop('Position', axis=1)
Y_test = test_df['Position']

In [176]:
X_train = X_train.drop('RaceCountry', axis=1)
X_train = X_train.drop('Year', axis=1)
X_test = X_test.drop('RaceCountry', axis=1)
X_test = X_test.drop('Year', axis=1)

In [177]:
x_train = X_train.drop(['Abbreviation', 'raceID'], axis = 1)
Z_train = X_train[['raceID']]
clusters_train = X_train['raceID']

In [178]:
#mrf = MERF(fixed_effects_model = LinearRegression(), max_iterations=30)
mrf.fit(x_train, Z_train, clusters_train, Y_train)

INFO     [merf.py:307] Training GLL is 1798.3726199915113 at iteration 1.
INFO     [merf.py:307] Training GLL is 1774.986836037651 at iteration 2.
INFO     [merf.py:307] Training GLL is 1770.384372461241 at iteration 3.
INFO     [merf.py:307] Training GLL is 1766.8062783736425 at iteration 4.
INFO     [merf.py:307] Training GLL is 1763.7753608996136 at iteration 5.
INFO     [merf.py:307] Training GLL is 1761.1336138538284 at iteration 6.
INFO     [merf.py:307] Training GLL is 1758.7881329778447 at iteration 7.
INFO     [merf.py:307] Training GLL is 1756.6771808268707 at iteration 8.
INFO     [merf.py:307] Training GLL is 1754.7570908973603 at iteration 9.
INFO     [merf.py:307] Training GLL is 1752.9956196284452 at iteration 10.
INFO     [merf.py:307] Training GLL is 1751.3681702713134 at iteration 11.
INFO     [merf.py:307] Training GLL is 1749.8555013718844 at iteration 12.
INFO     [merf.py:307] Training GLL is 1748.4422572239962 at iteration 13.
INFO     [merf.py:307] Training GLL is 1747.1159802090654 at iteration 14.
INFO     [merf.py:307] Training GLL is 1745.8664219582035 at iteration 15.
INFO     [merf.py:307] Training GLL is 1744.6850489738613 at iteration 16.
INFO     [merf.py:307] Training GLL is 1743.564679643732 at iteration 17.
INFO     [merf.py:307] Training GLL is 1742.4992126330883 at iteration 18.
INFO     [merf.py:307] Training GLL is 1741.4834203056498 at iteration 19.
INFO     [merf.py:307] Training GLL is 1740.5127893203246 at iteration 20.
INFO     [merf.py:307] Training GLL is 1739.5833960298007 at iteration 21.
INFO     [merf.py:307] Training GLL is 1738.6918079381142 at iteration 22.
INFO     [merf.py:307] Training GLL is 1737.835004934987 at iteration 23.
INFO     [merf.py:307] Training GLL is 1737.0103157242856 at iteration 24.
INFO     [merf.py:307] Training GLL is 1736.215366057332 at iteration 25.
INFO     [merf.py:307] Training GLL is 1735.4480362327731 at iteration 26.
INFO     [merf.py:307] Training GLL is 1734.706425939836 at iteration 27.
INFO     [merf.py:307] Training GLL is 1733.988824972167 at iteration 28.
INFO     [merf.py:307] Training GLL is 1733.2936886731823 at iteration 29.
INFO     [merf.py:307] Training GLL is 1732.6196172237753 at iteration 30.

In [179]:
train_preds = mrf.predict(x_train, Z_train, clusters_train)

In [180]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(Y_train, train_preds)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_train, train_preds)
r2 = r2_score(Y_train, train_preds)

# Print the performance metrics
print("Test MSE:", mse)
print("Test RMSE:", rmse)
print("Test MAE:", mae)
print("Test R-squared:", r2)

Test MSE: 8.27348915822779
Test RMSE: 2.8763673545338033
Test MAE: 2.259793609210368
Test R-squared: 0.7382129081749542

# Test Dataset

In [181]:
x_test = X_test.drop(['Abbreviation', 'raceID'], axis = 1)
Z_test = X_test[['raceID']]
clusters_test = X_test['raceID']

In [182]:
y_pred = mrf.predict(x_test, Z_test, clusters_test)

In [183]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)

# Print the performance metrics
print("Test MSE:", mse)
print("Test RMSE:", rmse)
print("Test MAE:", mae)
print("Test R-squared:", r2)

Test MSE: 7.302172787094027
Test RMSE: 2.7022532795972376
Test MAE: 2.1726833375904095
Test R-squared: 0.7686064777239628

In [184]:
actual_values = Y_test
predictions = y_pred
# Calculate the mean of actual values
mean_actual = sum(actual_values) / len(actual_values)

# Calculate SSE and SST
sse = sum((actual - pred) ** 2 for actual, pred in zip(actual_values, predictions))
sst = sum((actual - mean_actual) ** 2 for actual in actual_values)

# Calculate R-squared
r2 = 1 - (sse / sst)
r2

0.768606477723963